In [1]:
import pandas as pd
import csv
import os

新增發病起始年

In [4]:
# drop other columns
df = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(NewData)2.csv') # 1955 new data

columns_keep = ['病歷號','hyperlipidemia (0或1)','年齡','性別','HTN (0或1)','BMI','血壓-收縮壓 (mmHg)','血壓-輸張壓 (mmHg)','糖化血色素 (%)','發病起始年']

df = df[columns_keep]
df = df.rename(columns = 
                                    {'病歷號':'ID','hyperlipidemia (0或1)':'hyperlipidemia','年齡':'Age','性別':'Gender','HTN (0或1)':'HTN',
                                    '血壓-收縮壓 (mmHg)':'SP','血壓-輸張壓 (mmHg)':'DP','糖化血色素 (%)':'HbA1c','發病起始年':'Years'})

df.to_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/Patient_2521(+Year).csv',index = False)

In [5]:
df

           ID  hyperlipidemia  Age  Gender  HTN    BMI   SP  DP  HbA1c   Years
0     4056646             1.0   65       1  0.0  25.30  148  79    7.5  2008.0
1     4171431             1.0   58       1  1.0  24.84  122  81    6.7  2014.0
2      126136             NaN   84       1  NaN  26.93  151  72    7.9  1992.0
3     2994711             NaN   54       1  NaN  30.81  149  83    6.7  2018.0
4     9531160             1.0   61       1  1.0  29.76  138  71    7.1  2002.0
...       ...             ...  ...     ...  ...    ...  ...  ..    ...     ...
2516  4135048             1.0   63       1  1.0  30.85  146  87    7.4  2013.0
2517  4002851             1.0   54       1  1.0  22.09  125  61    9.7  2001.0
2518  4028325            10.0   63       2  1.0  24.14  153  86    5.9  2006.0
2519  4394965             1.0   58       1  1.0  29.94  117  75   10.2  2013.0
2520   357444             NaN   79       1  NaN  22.79  131  67    7.0  1987.0

[2521 rows x 10 columns]

select labels

In [21]:
# drop other columns
df = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(NewData)2.csv') # 1955 new data

# columns_keep = ['病歷號','年齡','性別']
columns_keep = ['病歷號','hyperlipidemia (0或1)','年齡','性別','HTN (0或1)','BMI','血壓-收縮壓 (mmHg)','血壓-輸張壓 (mmHg)','糖化血色素 (%)']

df = df[columns_keep]
df = df.rename(columns = 
                                    {'病歷號':'ID','hyperlipidemia (0或1)':'hyperlipidemia','年齡':'Age','性別':'Gender','HTN (0或1)':'HTN',
                                    '血壓-收縮壓 (mmHg)':'SP','血壓-輸張壓 (mmHg)':'DP','糖化血色素 (%)':'HbA1c'})

df.to_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/Patient_2521.csv',index = False)

In [22]:
df

           ID  hyperlipidemia  Age  Gender  HTN    BMI   SP  DP  HbA1c
0     4056646             1.0   65       1  0.0  25.30  148  79    7.5
1     4171431             1.0   58       1  1.0  24.84  122  81    6.7
2      126136             NaN   84       1  NaN  26.93  151  72    7.9
3     2994711             NaN   54       1  NaN  30.81  149  83    6.7
4     9531160             1.0   61       1  1.0  29.76  138  71    7.1
...       ...             ...  ...     ...  ...    ...  ...  ..    ...
2516  4135048             1.0   63       1  1.0  30.85  146  87    7.4
2517  4002851             1.0   54       1  1.0  22.09  125  61    9.7
2518  4028325            10.0   63       2  1.0  24.14  153  86    5.9
2519  4394965             1.0   58       1  1.0  29.94  117  75   10.2
2520   357444             NaN   79       1  NaN  22.79  131  67    7.0

[2521 rows x 9 columns]

# Color

In [14]:
# create a new csv file
csv_file = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/ labels4_(2521+Year).csv'
header = ['ID','Gender']

with open(csv_file,'w',newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)

# Loading Fundus Images
ImageFilePath = '/home/john/network/RETFound/data/data(SUM)/'   

ImageFileNames = [filename for filename in os.listdir(ImageFilePath)]

csv_file_outcome = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/Patient_2521(+Year).csv'  #Patient_2521(+Year).csv  Patient_2521.csv
df = pd.read_csv(csv_file_outcome)

image_folder = '/home/john/network/RETFound/data/data(SUM)/'

image_filenames = [filename for filename in os.listdir(image_folder)]
df['ID'] = image_filenames

df.to_csv(csv_file,index=False)

# Blood

In [24]:
# create a new csv file
csv_file = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/GAN_2521.csv' ##This
header = ['ID','Gender']

with open(csv_file,'w',newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)

# Loading Fundus Images
ImageFilePath = '/home/john/network/RETFound/data/data(SUM)_GAN/'
# ImageFilePath = '../model/Blood/'
ImageFileNames = [filename for filename in os.listdir(ImageFilePath)]

csv_file_outcome =  '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/Patient_2521(+Year).csv' 
df = pd.read_csv(csv_file_outcome)

image_folder = '/home/john/network/RETFound/data/data(SUM)_GAN/'

image_filenames = [filename for filename in os.listdir(image_folder)]
df['ID'] = image_filenames

df.to_csv(csv_file,index=False)

In [33]:
GANcsv = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/GAN_2521.csv')

In [34]:
GANcsv

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years
0,Low_ROI_4255213_07_R_20230815.png,1.0,65,1,0.0,25.30,148,79,7.5,2008.0
1,Low_ROI_4006452_03_L_20191127.png,1.0,58,1,1.0,24.84,122,81,6.7,2014.0
2,Low_ROI_4056108-02-L-20161220.png,NaN,84,1,NaN,26.93,151,72,7.9,1992.0
3,Low_ROI_4945112-04-L-20190507.png,NaN,54,1,NaN,30.81,149,83,6.7,2018.0
4,Low_ROI_4138836_01_R_20170306.png,1.0,61,1,1.0,29.76,138,71,7.1,2002.0
...,...,...,...,...,...,...,...,...,...,...
2516,Low_ROI_4826070_03_L_20200817.png,1.0,63,1,1.0,30.85,146,87,7.4,2013.0
2517,Low_ROI_4019674-12-L-20200715.png,1.0,54,1,1.0,22.09,125,61,9.7,2001.0
2518,Low_ROI_7004280_03_R_20220208.png,10.0,63,2,1.0,24.14,153,86,5.9,2006.0
2519,Low_ROI_4075259-06-R-20230103.png,1.0,58,1,1.0,29.94,117,75,10.2,2013.0
2520,Low_ROI_1927433-03-L-20220712.png,NaN,79,1,NaN,22.79,131,67,7.0,1987.0

In [35]:
GANcsv['Howlong'] = ""
GANcsv

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years,Howlong
0,Low_ROI_4255213_07_R_20230815.png,1.0,65,1,0.0,25.30,148,79,7.5,2008.0,
1,Low_ROI_4006452_03_L_20191127.png,1.0,58,1,1.0,24.84,122,81,6.7,2014.0,
2,Low_ROI_4056108-02-L-20161220.png,NaN,84,1,NaN,26.93,151,72,7.9,1992.0,
3,Low_ROI_4945112-04-L-20190507.png,NaN,54,1,NaN,30.81,149,83,6.7,2018.0,
4,Low_ROI_4138836_01_R_20170306.png,1.0,61,1,1.0,29.76,138,71,7.1,2002.0,
...,...,...,...,...,...,...,...,...,...,...,...
2516,Low_ROI_4826070_03_L_20200817.png,1.0,63,1,1.0,30.85,146,87,7.4,2013.0,
2517,Low_ROI_4019674-12-L-20200715.png,1.0,54,1,1.0,22.09,125,61,9.7,2001.0,
2518,Low_ROI_7004280_03_R_20220208.png,10.0,63,2,1.0,24.14,153,86,5.9,2006.0,
2519,Low_ROI_4075259-06-R-20230103.png,1.0,58,1,1.0,29.94,117,75,10.2,2013.0,
2520,Low_ROI_1927433-03-L-20220712.png,NaN,79,1,NaN,22.79,131,67,7.0,1987.0,

In [36]:
for i in range(len(GANcsv.ID)):
    GANcsv['Howlong'][i] =    int(GANcsv.ID[i][-12:-8] ) - GANcsv.Years[i]

GANcsv.to_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(2521)GAN.csv')

GANcsv

/tmp/ipykernel_32674/3352624498.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GANcsv['Howlong'][i] =    int(GANcsv.ID[i][-12:-8] ) - GANcsv.Years[i]

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years,Howlong
0,Low_ROI_4255213_07_R_20230815.png,1.0,65,1,0.0,25.30,148,79,7.5,2008.0,15.0
1,Low_ROI_4006452_03_L_20191127.png,1.0,58,1,1.0,24.84,122,81,6.7,2014.0,5.0
2,Low_ROI_4056108-02-L-20161220.png,NaN,84,1,NaN,26.93,151,72,7.9,1992.0,24.0
3,Low_ROI_4945112-04-L-20190507.png,NaN,54,1,NaN,30.81,149,83,6.7,2018.0,1.0
4,Low_ROI_4138836_01_R_20170306.png,1.0,61,1,1.0,29.76,138,71,7.1,2002.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...
2516,Low_ROI_4826070_03_L_20200817.png,1.0,63,1,1.0,30.85,146,87,7.4,2013.0,7.0
2517,Low_ROI_4019674-12-L-20200715.png,1.0,54,1,1.0,22.09,125,61,9.7,2001.0,19.0
2518,Low_ROI_7004280_03_R_20220208.png,10.0,63,2,1.0,24.14,153,86,5.9,2006.0,16.0
2519,Low_ROI_4075259-06-R-20230103.png,1.0,58,1,1.0,29.94,117,75,10.2,2013.0,10.0
2520,Low_ROI_1927433-03-L-20220712.png,NaN,79,1,NaN,22.79,131,67,7.0,1987.0,35.0

In [5]:
# drop other columns
df = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(Blood).csv')

columns_keep = ['病歷號','年齡','性別']

df = df[columns_keep]
df = df.rename(columns = {'病歷號':'ID','年齡':'Age','性別':'Gender'})

df.to_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(Blood).csv',index = False)

# For Pytorch data

In [52]:
# csv_file_624 = pd.read_csv('/home/john/network/Fundus/model/csv/labels4_(648).csv' )
# csv_file_624

csv_file_2521 = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/labels4_(2521+Year).csv' )  # labels4_(+Year).csv labels4_(2521).csv
csv_file_2521

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years
0,ROI_4056646_04_R_20190830.jpg,1.0,65,1,0.0,25.30,148,79,7.5,2008.0
1,ROI_4171431-01-L-20190719.jpg,1.0,58,1,1.0,24.84,122,81,6.7,2014.0
2,ROI_126136_07_L_20230411.jpg,NaN,84,1,NaN,26.93,151,72,7.9,1992.0
3,ROI_2994711_03_L_20230707.jpg,NaN,54,1,NaN,30.81,149,83,6.7,2018.0
4,ROI_9531160-02-R-20160302.jpg,1.0,61,1,1.0,29.76,138,71,7.1,2002.0
...,...,...,...,...,...,...,...,...,...,...
2516,ROI_4135048-07-L-20230721.jpg,1.0,63,1,1.0,30.85,146,87,7.4,2013.0
2517,ROI_4002851-01-R-20121025.jpg,1.0,54,1,1.0,22.09,125,61,9.7,2001.0
2518,ROI_4028325_02_L_20190813.jpg,10.0,63,2,1.0,24.14,153,86,5.9,2006.0
2519,ROI_4394965_01_L_20160622.jpg,1.0,58,1,1.0,29.94,117,75,10.2,2013.0
2520,ROI_357444_04_L_20200902.jpg,NaN,79,1,NaN,22.79,131,67,7.0,1987.0

In [53]:
csv_file_2521['Howlong'] = ""

In [54]:
csv_file_2521

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years,Howlong
0,ROI_4056646_04_R_20190830.jpg,1.0,65,1,0.0,25.30,148,79,7.5,2008.0,
1,ROI_4171431-01-L-20190719.jpg,1.0,58,1,1.0,24.84,122,81,6.7,2014.0,
2,ROI_126136_07_L_20230411.jpg,NaN,84,1,NaN,26.93,151,72,7.9,1992.0,
3,ROI_2994711_03_L_20230707.jpg,NaN,54,1,NaN,30.81,149,83,6.7,2018.0,
4,ROI_9531160-02-R-20160302.jpg,1.0,61,1,1.0,29.76,138,71,7.1,2002.0,
...,...,...,...,...,...,...,...,...,...,...,...
2516,ROI_4135048-07-L-20230721.jpg,1.0,63,1,1.0,30.85,146,87,7.4,2013.0,
2517,ROI_4002851-01-R-20121025.jpg,1.0,54,1,1.0,22.09,125,61,9.7,2001.0,
2518,ROI_4028325_02_L_20190813.jpg,10.0,63,2,1.0,24.14,153,86,5.9,2006.0,
2519,ROI_4394965_01_L_20160622.jpg,1.0,58,1,1.0,29.94,117,75,10.2,2013.0,
2520,ROI_357444_04_L_20200902.jpg,NaN,79,1,NaN,22.79,131,67,7.0,1987.0,

In [55]:
csv_file_2521.ID[0][-12:-8]

'2019'

In [56]:
count = int(csv_file_2521.ID[0][-12:-8] ) - csv_file_2521.Years[0]
count

11.0

In [57]:
for i in range(len(csv_file_2521.ID)):
    csv_file_2521['Howlong'][i] =    int(csv_file_2521.ID[i][-12:-8] ) - csv_file_2521.Years[i]

# csv_file_2521.to_csv('SelectPatientOutcome(2521).csv')
csv_file_2521

/tmp/ipykernel_32674/2954110181.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_2521['Howlong'][i] =    int(csv_file_2521.ID[i][-12:-8] ) - csv_file_2521.Years[i]

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years,Howlong
0,ROI_4056646_04_R_20190830.jpg,1.0,65,1,0.0,25.30,148,79,7.5,2008.0,11.0
1,ROI_4171431-01-L-20190719.jpg,1.0,58,1,1.0,24.84,122,81,6.7,2014.0,5.0
2,ROI_126136_07_L_20230411.jpg,NaN,84,1,NaN,26.93,151,72,7.9,1992.0,31.0
3,ROI_2994711_03_L_20230707.jpg,NaN,54,1,NaN,30.81,149,83,6.7,2018.0,5.0
4,ROI_9531160-02-R-20160302.jpg,1.0,61,1,1.0,29.76,138,71,7.1,2002.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...
2516,ROI_4135048-07-L-20230721.jpg,1.0,63,1,1.0,30.85,146,87,7.4,2013.0,10.0
2517,ROI_4002851-01-R-20121025.jpg,1.0,54,1,1.0,22.09,125,61,9.7,2001.0,11.0
2518,ROI_4028325_02_L_20190813.jpg,10.0,63,2,1.0,24.14,153,86,5.9,2006.0,13.0
2519,ROI_4394965_01_L_20160622.jpg,1.0,58,1,1.0,29.94,117,75,10.2,2013.0,3.0
2520,ROI_357444_04_L_20200902.jpg,NaN,79,1,NaN,22.79,131,67,7.0,1987.0,33.0

In [16]:
Good = []

for i in range(0,len(csv_file_2521.ID)):
    if csv_file_2521.Age[i]  < 65 and csv_file_2521.hyperlipidemia[i] == 0 and csv_file_2521.HTN[i] == 0 and csv_file_2521.BMI[i] < 24 and csv_file_2521.HbA1c[i] < 7.0 and csv_file_2521.Howlong[i] < 10 :
        Good.append(csv_file_2521.ID[i])

print(len(Good))

14

In [18]:
for i in Good:
    print(i)

ROI_4046559-04-L-20190916.jpg
ROI_7075752-02-L-20230620.jpg
ROI_4046559-01-L-20150605.jpg
ROI_4046559-05-L-20201130.jpg
ROI_7075752-01-L-20221117.jpg
ROI_4046559-01-R-20150605.jpg
ROI_4046559-03-L-20181108.jpg
ROI_4046559-05-R-20201130.jpg
ROI_4046559-02-L-20170817.jpg
ROI_7075752-01-R-20221117.jpg
ROI_4046559-02-R-20170817.jpg
ROI_4046559-03-R-20181108.jpg
ROI_4046559-04-R-20190916.jpg
ROI_7075752-02-R-20230620.jpg

In [17]:
Good[0]

'ROI_4046559-04-L-20190916.jpg'

In [58]:
Bad = []

for i in range(0,len(csv_file_2521.ID)):
    if csv_file_2521.Age[i]  >= 65 and csv_file_2521.hyperlipidemia[i] == 1 and csv_file_2521.HTN[i] == 1 and csv_file_2521.BMI[i] >= 24 and csv_file_2521.HbA1c[i] >= 7.0 and csv_file_2521.Howlong[i] >= 10 :
        Bad.append(csv_file_2521.ID[i])

print(len(Bad))

157

In [59]:
for i in Bad:
    print(i)

ROI_4531547-01-L-20211019.jpg
ROI_7199813-09-R-20220419.jpg
ROI_4945112-01-L-20160511.jpg
ROI_4531547-02-L-20221011.jpg
ROI_4049344_03_R_20180330.jpg
ROI_4009801-09-R-20190410.jpg
ROI_4181235-04-L-20110510.jpg
ROI_4127039_01_R_20200703.jpg
ROI_4900769-03-R-20161115.jpg
ROI_4945112-04-L-20190507.jpg
ROI_4111178_01_L_20160509.jpg
ROI_4900769-05-L-20190515.jpg
ROI_4051451-13-R-20201007.jpg
ROI_4049344_04_L_20190606.jpg
ROI_4900769-08-R-20220719.jpg
ROI_4051451-04-L-20091126.jpg
ROI_4051451-06-L-20120417.jpg
ROI_4049344_05_R_20200807.jpg
ROI_4900769-02-L-20151208.jpg
ROI_4111178_08_R_20230901.jpg
ROI_4049344_07_L_20230106.jpg
ROI_4127039_02_R_20210222.jpg
ROI_4181235-06-L-20140107.jpg
ROI_4111178_02_R_20170704.jpg
ROI_4945112-07-L-20220930.jpg
ROI_4051451-07-R-20130724.jpg
ROI_4009801-12-L-20221027.jpg
ROI_4141750_04_L_20211013.jpg
ROI_4900769-07-R-20210915.jpg
ROI_7151219_02_R_20220729.jpg
ROI_4051451-08-R-20140902.jpg
ROI_4141750_05_R_20220622.jpg
ROI_4051451-05-R-20110208.jpg
ROI_4891579-02-R-20210312.jpg
ROI_7151219_01_R_20211221.jpg
ROI_4945112-08-R-20230915.jpg
ROI_4049344_02_R_20170203.jpg
ROI_4049344_06_R_20211021.jpg
ROI_4087480_01_R_20230113.jpg
ROI_4846488_01_R_20160728.jpg
ROI_4181235-07-L-20150227.jpg
ROI_4945112-04-R-20190507.jpg
ROI_4051451-08-L-20140902.jpg
ROI_4127039_03_R_20220422.jpg
ROI_4891579-02-L-20210312.jpg
ROI_4051451-15-L-20221108.jpg
ROI_4945112-06-R-20211020.jpg
ROI_7199813-10-L-20230613.jpg
ROI_4846488_01_L_20160728.jpg
ROI_4900769-08-L-20220719.jpg
ROI_4846488_05_L_20201111.jpg
ROI_4900769-09-L-20230725.jpg
ROI_4531547-02-R-20221011.jpg
ROI_4846488_06_L_20220308.jpg
ROI_4127039_02_L_20210222.jpg
ROI_4049344_03_L_20180330.jpg
ROI_4111178_04_L_20190828.jpg
ROI_4900769-05-R-20190515.jpg
ROI_7199813-10-R-20230613.jpg
ROI_4127039_04_L_20230620.jpg
ROI_4111178_06_R_20211101.jpg
ROI_4111178_03_L_20180718.jpg
ROI_4111178_01_R_20160509.jpg
ROI_4127039_01_L_20200703.jpg
ROI_4051451-01-R-20061107.jpg
ROI_4141750_03_L_20200923.jpg
ROI_4181235-08-L-20160527.jpg
ROI_4049344_01_R_20160108.jpg
ROI_4900769-01-L-20150224.jpg
ROI_4900769-09-R-20230725.jpg
ROI_4127039_03_L_20220422.jpg
ROI_4945112-07-R-20220930.jpg
ROI_4111178_02_L_20170704.jpg
ROI_4945112-02-L-20170208.jpg
ROI_4051451-05-L-20110208.jpg
ROI_4009801-12-R-20221027.jpg
ROI_4900769-06-L-20200527.jpg
ROI_4141750_05_L_20220622.jpg
ROI_4111178_08_L_20230901.jpg
ROI_4111178_05_R_20200715.jpg
ROI_4945112-05-L-20200805.jpg
ROI_4051451-02-R-20070918.jpg
ROI_4049344_04_R_20190606.jpg
ROI_4009801-10-R-20200603.jpg
ROI_4945112-03-R-20180321.jpg
ROI_7151219_02_L_20220729.jpg
ROI_4181235-05-L-20120803.jpg
ROI_4051451-09-R-20151127.jpg
ROI_4846488_02_L_20170919.jpg
ROI_4111178_05_L_20200715.jpg
ROI_4111178_07_R_20220825.jpg
ROI_4111178_03_R_20180718.jpg
ROI_4945112-08-L-20230915.jpg
ROI_4141750_03_R_20200923.jpg
ROI_4945112-06-L-20211020.jpg
ROI_4051451-04-R-20091126.jpg
ROI_4900769-07-L-20210915.jpg
ROI_4900769-04-R-20180214.jpg
ROI_4111178_06_L_20211101.jpg
ROI_4181235-04-R-20110510.jpg
ROI_4945112-01-R-20160511.jpg
ROI_4049344_06_L_20211021.jpg
ROI_4051451-03-R-20081112.jpg
ROI_7199813-09-L-20220419.jpg
ROI_4181235-07-R-20150227.jpg
ROI_4141750_04_R_20211013.jpg
ROI_4051451-14-R-20211001.jpg
ROI_4049344_07_R_20230106.jpg
ROI_4111178_04_R_20190828.jpg
ROI_4945112-03-L-20180321.jpg
ROI_4900769-06-R-20200527.jpg
ROI_4891579-01-R-20150930.jpg
ROI_4051451-13-L-20201007.jpg
ROI_4891579-03-L-20220526.jpg
ROI_4945112-02-R-20170208.jpg
ROI_4051451-12-R-20190614.jpg
ROI_4051451-12-L-20190614.jpg
ROI_4009801-11-L-20210907.jpg
ROI_4051451-07-L-20130724.jpg
ROI_4891579-04-R-20230103.jpg
ROI_4846488_05_R_20201111.jpg
ROI_4111178_07_L_20220825.jpg
ROI_4846488_07_L_20230112.jpg
ROI_4009801-09-L-20190410.jpg
ROI_4051451-03-L-20081112.jpg
ROI_4891579-04-L-20230103.jpg
ROI_4846488_03_R_20180905.jpg
ROI_4009801-11-R-20210907.jpg
ROI_4051451-06-R-20120417.jpg
ROI_4087480_01_L_20230113.jpg
ROI_4846488_04_R_20191023.jpg
ROI_4900769-03-L-20161115.jpg
ROI_4846488_04_L_20191023.jpg
ROI_7151219_01_L_20211221.jpg
ROI_4531547-03-L-20230925.jpg
ROI_4900769-1-R-20150224.jpg
ROI_4127039_04_R_20230620.jpg
ROI_4900769-04-L-20180214.jpg
ROI_4531547-01-R-20211019.jpg
ROI_4051451-15-R-20221108.jpg
ROI_4051451-01-L-20061107.jpg
ROI_4846488_02_R_20170919.jpg
ROI_4181235-05-R-20120803.jpg
ROI_4181235-08-R-20160527.jpg
ROI_4945112-05-R-20200805.jpg
ROI_4846488_06_R_20220308.jpg
ROI_4051451-02-L-20070918.jpg
ROI_4049344_01_L_20160108.jpg
ROI_4531547-03-R-20230925.jpg
ROI_4846488_03_L_20180905.jpg
ROI_4891579-01-L-20150930.jpg
ROI_4009801-10-L-20200603.jpg
ROI_4049344_02_L_20170203.jpg
ROI_4181235-06-R-20140107.jpg
ROI_4900769-02-R-20151208.jpg
ROI_4051451-14-20211001.jpg
ROI_4891579-03-R-20220526.jpg

In [15]:
Bad[0]

'ROI_4531547-01-L-20211019.jpg'

In [43]:
medians = csv_file_2521["Howlong"].median()
medians

10.0

In [26]:
type(csv_file_2521.Years[0])

numpy.float64

In [22]:
len(csv_file_2521.ID)

2521

# Gender statistical

In [29]:
other = 0
countM = 0
countF = 0

for i in range(0,len(csv_file_2521.ID)):

    if csv_file_2521.Gender[i]  == 1:
        countM += 1

    elif csv_file_2521.Gender[i]  == 2:
        countF += 1

    else: 
        other += 1

print("Male : ",countM)
print("Female : ",countF)
print("other : ",other)

Male :  1144
Female :  1377
other :  0

# Age statistical

In [28]:
other = 0
AgeO = 0
AgeN = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.Age[i]  >= 65:
            AgeO += 1

        elif csv_file_2521.Age[i]  <  65:
            AgeN += 1

        else: 
            other += 1

print("Age_old : ",AgeO)
print("Age_NotOld : ",AgeN)
print("other : ",other)

Age_old :  1487
Age_NotOld :  1034
other :  0

# BMI statistical

In [31]:
other = 0
BMI_Fat = 0
BMI_NotFat = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.BMI[i]  >= 24:
            BMI_Fat += 1

        elif csv_file_2521.BMI[i]  < 24:
            BMI_NotFat += 1

        else: 
            other += 1

print(">= 24 : ",BMI_Fat)
print("< 24 : ",BMI_NotFat)
print("other : ",other)

>= 24 :  1554
< 24 :  967
other :  0

# HbA1c statistical

In [32]:
other = 0
HbA1c_b7 = 0
HbA1c_s7 = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.HbA1c[i]  >= 7:
            HbA1c_b7 += 1

        elif csv_file_2521.HbA1c[i]  < 7:
            HbA1c_s7 += 1

        else: 
            other += 1

print(">= 7 : ",HbA1c_b7)
print("< 7 : ",HbA1c_s7)
print("other : ",other)

>= 7 :  1364
< 7 :  1101
other :  56

In [34]:
other = 0
HbA1c_b8 = 0
HbA1c_s8 = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.HbA1c[i]  >= 8:
            HbA1c_b8 += 1

        elif csv_file_2521.HbA1c[i]  < 8:
            HbA1c_s8 += 1

        else: 
            other += 1

print(">= 8 : ",HbA1c_b8)
print("< 8 : ",HbA1c_s8)
print("other : ",other)

>= 8 :  514
< 8 :  1951
other :  56

# HTN statistical

In [36]:
other = 0
htn_0= 0
htn_1 = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.HTN[i]  == 1:
            htn_0 += 1

        elif csv_file_2521.HTN[i]  == 0:
            htn_1 += 1

        else: 
            other += 1

print("0 : ",htn_0)
print("1 : ",htn_1)
print("other : ",other)

0 :  1167
1 :  777
other :  577

# hyperlipidemia statistical

In [30]:
other = 0
hyperlipidemia_0 = 0
hyperlipidemia_1 = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.hyperlipidemia[i]  == 1:
            hyperlipidemia_1 += 1

        elif csv_file_2521.hyperlipidemia[i]  == 0:
            hyperlipidemia_0 += 1

        else: 
            other += 1

print("0 : ",hyperlipidemia_0)
print("1 : ",hyperlipidemia_1)
print("other : ",other)

0 :  137
1 :  1800
other :  584

# Years statistical

In [49]:
other = 0
Big10 = 0
Small10 = 0

for i in range(0,len(csv_file_2521.ID)):

        if csv_file_2521.Howlong[i]  >= 10:
            Big10 += 1

        elif csv_file_2521.Howlong[i]  < 10:
            Small10 += 1

        else: 
            other += 1

print(">= 10 : ",Big10)
print("< 10 : ",Small10)
print("other : ",other)

>= 10 :  1284
< 10 :  1206
other :  31

# data auto move (model label)

In [57]:
import cv2

# color

In [44]:
# image_folder_py = '/home/john/network/Fundus/model/Color/dataset(624)/'
image_folder_py = '/home/john/network/RETFound/data/data(SUM)/'

output_directory_HTN_0 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HTN/0/'  #215
output_directory_HTN_1 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HTN/1/'  #409

output_directory_Gender_1 = '/home/john/network/RETFound/RETFound_MAE-main/data/Fundus_I/Gender/Male/'       #285
output_directory_Gender_2 = '/home/john/network/RETFound/RETFound_MAE-main/data/Fundus_I/Gender/Female/'  #339

output_directory_hyperlipidemia_0 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/hyperlipidemia/0/' #83
output_directory_hyperlipidemia_1 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/hyperlipidemia/1/' #541

output_directory_HbA1c_High_8 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HbA1c/8.0/High/' # 139
output_directory_HbA1c_NotHigh_8 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HbA1c/8.0/NotHigh/' # 467

output_directory_HbA1c_High_7 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HbA1c/7.0/High/' # 
output_directory_HbA1c_NotHigh_7 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HbA1c/7.0/NotHigh/' # 467

output_directory_Age_old = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/Age/Old/' #300
output_directory_Age_notold = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/Age/NotOld/' #324

output_directory_BMI_Fat = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/BMI/Fat/' # 403 
output_directory_BMI_Notfat = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/BMI/NotFat' # 221

output_directory_MAP_High = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/MAP/106/High/' # 49
output_directory_MAP_NotHigh = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/MAP/106/NotHigh' # 575 

output_directory_MAP_High_96 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/MAP/96/High/' # 257
output_directory_MAP_NotHigh_96 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/MAP/96/NotHigh' # 367 

output_directory_Year_big = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/Year/2010_big/' # 
output_directory_Year_small = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/Year/2010_small' # 

output_directory_Long = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HowLong/Long/' # 
output_directory_NotLong = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/data/HowLong/NotLong' #

In [ ]:
for i in range(0,len(csv_file_2521.ID)):

    if csv_file_2521.HTN[i] == 1.0:
        filename = csv_file_2521.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_HTN_1, filename)
        cv2.imwrite(output_path, image)
    
    if csv_file_2521.HTN[i] == 0.0:
        filename = csv_file_2521.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_HTN_0, filename)
        cv2.imwrite(output_path, image)
    
print("Done")

In [ ]:
for i in range(0,len(csv_file_2521.ID)):

    if csv_file_2521.Howlong[i] >= 10:
        filename = csv_file_2521.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_Long, filename)
        cv2.imwrite(output_path, image)
    
    if csv_file_2521.Howlong[i] < 10:
        filename = csv_file_2521.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_NotLong, filename)
        cv2.imwrite(output_path, image)
    
print("Done")

# GAN

In [4]:
# image_folder_py = '/home/john/network/Fundus/model/Color/dataset(624)/'
image_folder_py = '/home/john/network/RETFound/data/data(SUM)_GAN/'

output_directory_HTN_0 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HTN/0/'  #215
output_directory_HTN_1 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HTN/1/'  #409

output_directory_Gender_1 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/Gender/Male/'       #285
output_directory_Gender_2 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/Gender/Female/'  #339

output_directory_hyperlipidemia_0 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/hyperlipidemia/0/' #83
output_directory_hyperlipidemia_1 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/hyperlipidemia/1/' #541

output_directory_HbA1c_High_8 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HbA1c/8.0/High/' # 139
output_directory_HbA1c_NotHigh_8 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HbA1c/8.0/NotHigh/' # 467

output_directory_HbA1c_High_7 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HbA1c/7.0/High/' # 
output_directory_HbA1c_NotHigh_7 = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HbA1c/7.0/NotHigh/' # 467

output_directory_Age_old = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/Age/Old/' #300
output_directory_Age_notold = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/Age/NotOld/' #324

output_directory_BMI_Fat = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/BMI/Fat/' # 403 
output_directory_BMI_Notfat = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/BMI/NotFat' # 221

output_directory_MAP_High = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/MAP/106/High/' # 49
output_directory_MAP_NotHigh = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/MAP/106/NotHigh' # 575 

output_directory_Long = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HowLong/Long/' # 
output_directory_NotLong = '/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/GAN_data/HowLong/NotLong' #

In [37]:
csv_file_2521_GAN = pd.read_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_I/csv/SelectPatientOutcome(2521)GAN.csv',index_col=0)

In [38]:
csv_file_2521_GAN

,ID,hyperlipidemia,Age,Gender,HTN,BMI,SP,DP,HbA1c,Years,Howlong
0,Low_ROI_4255213_07_R_20230815.png,1.0,65,1,0.0,25.30,148,79,7.5,2008.0,15.0
1,Low_ROI_4006452_03_L_20191127.png,1.0,58,1,1.0,24.84,122,81,6.7,2014.0,5.0
2,Low_ROI_4056108-02-L-20161220.png,NaN,84,1,NaN,26.93,151,72,7.9,1992.0,24.0
3,Low_ROI_4945112-04-L-20190507.png,NaN,54,1,NaN,30.81,149,83,6.7,2018.0,1.0
4,Low_ROI_4138836_01_R_20170306.png,1.0,61,1,1.0,29.76,138,71,7.1,2002.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...
2516,Low_ROI_4826070_03_L_20200817.png,1.0,63,1,1.0,30.85,146,87,7.4,2013.0,7.0
2517,Low_ROI_4019674-12-L-20200715.png,1.0,54,1,1.0,22.09,125,61,9.7,2001.0,19.0
2518,Low_ROI_7004280_03_R_20220208.png,10.0,63,2,1.0,24.14,153,86,5.9,2006.0,16.0
2519,Low_ROI_4075259-06-R-20230103.png,1.0,58,1,1.0,29.94,117,75,10.2,2013.0,10.0
2520,Low_ROI_1927433-03-L-20220712.png,NaN,79,1,NaN,22.79,131,67,7.0,1987.0,35.0

In [39]:
import cv2

In [43]:
for i in range(0,len(csv_file_2521_GAN.ID)):

    if csv_file_2521_GAN.hyperlipidemia[i] == 0.0:
        filename = csv_file_2521_GAN.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_hyperlipidemia_0, filename)
        cv2.imwrite(output_path, image)
    
    if csv_file_2521_GAN.hyperlipidemia[i] == 1.0:
        filename = csv_file_2521_GAN.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_hyperlipidemia_1, filename)
        cv2.imwrite(output_path, image)
    
print("Done")

Done

In [48]:
for i in range(0,len(csv_file_2521_GAN.ID)):

    if csv_file_2521_GAN.Age[i] >=65:
        filename = csv_file_2521_GAN.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_Age_old, filename)
        cv2.imwrite(output_path, image)
    
    if csv_file_2521_GAN.Age[i] < 65:
        filename = csv_file_2521_GAN.ID[i]
        image_path = os.path.join(image_folder_py,filename)
        image = cv2.imread(image_path)
        output_path = os.path.join(output_directory_Age_notold, filename)
        cv2.imwrite(output_path, image)
    
print("Done")

Done

# Move file togeter

In [2]:
import os
import shutil


source_folder = '/home/john/network/RETFound/data/1201_NewData/'
destination_folder = '/home/john/network/RETFound/data/1201_data'


def move_file(source_folder,destination_folder):
    count = 0
    for root,sub,files in os.walk(source_folder):
        for file in files:
            source_folder_path = os.path.join(root,file)
            destination_file_path = os.path.join(destination_folder,file)
            shutil.copy2(source_folder_path,destination_file_path)
            count += 1
    print("Image files number: ",count)

move_file(source_folder,destination_folder)

Image files number:  1165